### ISSUE TITLE
Debug Soft Actor-Critic

### ISSUE THREAD

**Issue by chrisohrstrom** [ChrisFugl/Shape-Memory-Alloy-Positioning#1]
The implementation is currently not correct. We need to figure out why and fix it.

Run with config/debug.yaml to test it. This configuration uses a very simple environment in which the goal is to move to 5, and the agent starts at a random position between 0 and 10. Actions are any number (positive and negative) and will cause the agent to move the specified amount. This should be fairly easy to learn. The hyperparameters might need to be tuned.

**Comment by wonjun-chung** [comment]
I got error when run python train.py configs/simulated.yaml
It raise SyntaxError in line 53, is it fine on your settings?

**Comment by wonjun-chung** [comment]
Oh, f-string method is for upper python 3.6
I fix it

**Comment by wonjun-chung** [comment]
I would like to know in what sense it is said that it is not implemented correctly.

**Comment by chrisohrstrom** [comment]
> I would like to know in what sense it is said that it is not implemented correctly.

Good point, I did not specify that. It is not implemented correctly in the sense that it is not learning anything. Loss seems to go up (when it should go down) as training progresses. I have tried to use different hyperparameters, and it did not change anything. It seems that there is a bug(s) in the code that prevents it from training correctly.

**Comment by shk0707** [comment]
Starting to work on this

**Comment by chrisohrstrom** [comment]
Found a bug. This doesn't fix everything, but it is a step in the right direction at least.

There was a bug in the calculation of the target of the Q-functions  (used in the Q-losses). The line used to be the following:

self.reward_scale * rewards * (1.0 - terminals) * self.discount_factor * value_next_observation

It has been changed to this:

self.reward_scale * rewards + (1.0 - terminals) * self.discount_factor * value_next_observation

Notice that one of the multiplier operators has been changed to addition.

**Comment by IbrahimYasir** [comment]
Changed the reward function based on direction of the goal. ext and gam are just used for scaling  
    def reward(self, state, action, next_state):
        new_distance_to_goal = abs(next_state[0] - self.config.goal_position)
        old_distance_to_goal = abs(state[0] - self.config.goal_position)
        distance = old_distance_to_goal - new_distance_to_goal
        direction = 0
        ext = 1
        gam = 0.1
        if (distance <0) :
            direction = 1
        if (direction == 1):
            similarity_to_goal = exp((ext -gam*new_distance_to_goal))
        if (direction != 1):
            similarity_to_goal = exp((-ext -gam* new_distance_to_goal))

        return similarity_to_goal

or something like 
    def reward(self, state, action, next_state):
        distance_to_goal = abs(next_state[0] - self.config.goal_position)
       scale = 5
        similarity_to_goal = 1 - (distance_to_goal/scale)*0.5
        return similarity_to_goal

**Comment by chrisohrstrom** [comment]
Done since we are using reference implementation now.
