### ISSUE TITLE
Log performance to tensorboard

### ISSUE THREAD

**Issue by chrisohrstrom** [ChrisFugl/Shape-Memory-Alloy-Positioning#2]
This task is important as we need to be able to diagnose the performance of our algorithm as it runs.

Setup tensorboard and log (at least) (the average) of following metrics:

* policy loss
* q1 loss
* q2 loss
* reward

It might also be a good idea to log position once we have the real time environment setup.

**Comment by wonjun-chung** [comment]
I will grab it
